### ISSUE TITLE
Update session not finding sessions to update

### ISSUE THREAD

**Issue by mrcodesx** [mordentral/AdvancedSessionsPlugin#18]
Can not update a session after creating it. Error `NO REGISTERED SESSIONS!` is being displayed.

I'm sending a PR to fix it, I've found the cause:

- The class used to **create** a session (`UCreateSessionCallbackProxyAdvanced`) is using `Helper.OnlineSub->GetSessionInterface()` to get a `IOnlineSession`. Let's call that instance **`IOnlineSession A`**.
- The class used to **update** as session (`UUpdateSessionCallbackProxyAdvanced`) is using `Online::GetSessionInterface(GetWorld())` to get a `IOnlineSession`. Let's call that instance **`IOnlineSession B`**.
- So two **different** instances of `IOnlineSession` are being created, each with its own and independent `TArray<FNamedOnlineSession> Sessions` variable which is used to keep track of the sessions being created and updated.
- When creating a session using **`IOnlineSession A`**, the array `Sessions` in it is being added 1 session but **`IOnlineSession B`**'s `Sessions` array still has 0 elements since it's another instance, so when trying to update a session the code `Sessions->GetNumSessions() < 1` evaluates to `true` and the error `NO REGISTERED SESSIONS!` is being shown making it impossible to update a session.

**Comment by mrcodesx** [comment]
This PR should fix it https://github.com/mordentral/AdvancedSessionsPlugin/pull/19

**Comment by mordentral** [comment]
what subsystem are you testing this on? update sessions hasn't really been touched in a long time and it has historically worked (though I have had random people mention it didn't for them). This sounds like a valid fix but before I look into it too much curious if there are specific subsystems I need to compare against.

**Comment by mrcodesx** [comment]
I'm testing it against a slightly modified version of the [NULL Subsystem](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/Online/OnlineSubsystemNull).

The issue should be reproducible with any other online subsystem though since the implementation of the function `IOnlineSession::GetNumSessions()` is the same in most of them:

```cpp
int32 FOnlineSessionRex::GetNumSessions()
{
	FScopeLock ScopeLock(&SessionLock);
	return Sessions.Num();
}
```

And that same `Sessions` variable is what's being referenced by [UpdateSessionCallbackProxyAdvanced](https://github.com/mordentral/AdvancedSessionsPlugin/blob/ec634238f8c93ae26758f67afca20f617fbd2477/AdvancedSessions/Source/AdvancedSessions/Private/UpdateSessionCallbackProxyAdvanced.cpp#L37) to determine whether or not to update the session.

**Comment by mordentral** [comment]
Curious, are you testing in editor or outside of it?

While I can see forcing world so that it works in editor, in editor spools up a "faux" session when PIE. Outside of editor both of those functions should return the same global session interface with a single entry.

**Comment by mrcodesx** [comment]
This issue I've only seen it on the editor. I'm going to do some tests in standalone and in a packaged project.

**Comment by mordentral** [comment]
Yes please do, it should function when packaged, the editor session gets in the way of a few things.

Im not against calling the world version so that PIE works with update session, however I want to make sure its what I think it is.

**Comment by sooroosh10** [comment]
Is there any possibility to update your plugins on UE5? That would be fantastic.

**Comment by mordentral** [comment]
> Is there any possibility to update your plugins on UE5? That would be fantastic.

Not sure what you mean, there are already UE5 preview 2 branches and binaries downloads available.

**Comment by mrcodesx** [comment]
> Curious, are you testing in editor or outside of it?
> 
> While I can see forcing world so that it works in editor, in editor spools up a "faux" session when PIE. Outside of editor both of those functions should return the same global session interface with a single entry.

I've just tested and can confirm that outside of editor, indeed, those functions return the same instance of the Online Subsystem, so that bug only happened within the Editor. I've seen the PR is merged, thanks.
