### ISSUE TITLE
C++ Example

### ISSUE THREAD

**Issue by gustavomassa** [mordentral/AdvancedSessionsPlugin#2]
Hello, thank you for this amazing plugin.

Do you have any example/project that uses this plugin calling directly the C++ functions?
Also, this plugin supports the Steam Sockets Plugin? [https://docs.unrealengine.com/en-US/Gameplay/Networking/HowTo/SteamSockets/index.html](https://docs.unrealengine.com/en-US/Gameplay/Networking/HowTo/SteamSockets/index.html)

**Comment by mordentral** [comment]
There is literally no reason to use this plugin with C++, the only point of the plugin is to expose c++ functions to BP, you already have access to everything in c++.

Also steam sockets is a networking layer drop in replacement and doesn't interact with the high level subsystem uses.

**Comment by gustavomassa** [comment]
Your code has useful functions that could be used with C++ to create a wrapper around the OnlineSubSystem API.
I mean create a simple wrapper that implements all the boilerplate necessary to initialize/configure the session, making available basic functions for session control, line create/start/find/join/destroy.
Also, I found that enabling steam sockets with the same configs does not work out of the box, giving errors when calling the GetResolvedConnectString function.

The documentation for session and steam integration is really a mess, so the idea is to have some service that works out of the box with basic configurations.
I will create a basic SessionService with Async/Future functions to avoid delegates/callbacks for easy usage.
