### ISSUE TITLE
UE5 Not Loading With Plugin

### ISSUE THREAD

**Issue by CardsAndGamesYT** [mordentral/AdvancedSessionsPlugin#22]
Hey, I'm trying to use the ue5 version of this plugin on my game. when i enabled the plugin i keep getting this pop up when i load the project.
![image](https://user-images.githubusercontent.com/74144694/154389133-b9fd840a-a1a2-4826-8246-c1881b621da1.png)
not sure what the issue is as there is only 1 version of ue5...
And just for some info, im using the UE5-Prerelease branch

**Comment by mordentral** [comment]
You have to compile the plugin for it, I don't have pre-compiled binaries for the EA engine.

**Comment by CardsAndGamesYT** [comment]
how could i do this?

**Comment by mordentral** [comment]
Load up the project in visual studio and build it for Development Editor

My vr plugins compilation tutorial is the same steps:

https://vreue4.com/documentation?section=installation

**Comment by CardsAndGamesYT** [comment]
Thankyou! :)
