### ISSUE TITLE
AdvancedSteamSessions missing dependency to plugin SteamSockets

### ISSUE THREAD

**Issue by olir** [mordentral/AdvancedSessionsPlugin#23]
I feel the plugin AdvancedSteamSessions is missing a dependency to plugin SteamSockets.
Without it and proper configuration dedicated servers in the internet are non-operational.

https://docs.unrealengine.com/4.27/en-US/InteractiveExperiences/Networking/HowTo/SteamSockets/

**Comment by mordentral** [comment]
Steam sockets is not a requirement of steam and dedicated servers work without it.
