### ISSUE TITLE
empty UniqueID

### ISSUE THREAD

**Issue by cslak** [mordentral/AdvancedSessionsPlugin#26]
In last 4.27.2 dedicated server returns UniqueID: <blank> Steam: UKNOWN
<img width="640" alt="serf" src="https://user-images.githubusercontent.com/1350430/157531133-1a7073ce-013f-4ff1-9f80-cb64b2caa933.png">
Purely using advanced steam sessions, with no steam sockets plugin enabled.

**Comment by cslak** [comment]
This issue is not present in 4.26

**Comment by mordentral** [comment]
There are multiple people I am aware of using dedicated servers with 4.27, and dedicated servers don't have a unique net ID anyway on steam.

**Comment by cslak** [comment]
im sorry not dedicated server, i believe this shows the uniqueID of a player, which is blank

**Comment by cslak** [comment]
also when client calls steampersonaname, always returns null in 4.27.2, but not in 4.26

**Comment by mordentral** [comment]
how soon did you check? if its another player and you are getting it from the player state, that array doesn't replicate right away.

**Comment by mordentral** [comment]
I can give it a test tomorrow, however I would have assumed I would have heard about this in the months of 4.27 being out.

**Comment by cslak** [comment]
Used delay node with 10 seconds

**Comment by cslak** [comment]
Good idea, let me try that now, I'll post screenshot in a sec

**Comment by cslak** [comment]
<img width="725" alt="cggnanme" src="https://user-images.githubusercontent.com/1350430/157731642-403595ec-a6cb-4ce9-935e-6a51896e8cb2.png">
this works when i host a session, but not when join a dedicated server(there is a is dedicated server note)

**Comment by cslak** [comment]
<img width="558" alt="playerarray" src="https://user-images.githubusercontent.com/1350430/157732700-732268d7-84b5-4439-bc2b-b9628f8b740b.png">
about to try this

**Comment by mordentral** [comment]
did you not implement the steam auth setup from here?: https://docs.unrealengine.com/4.27/en-US/ProgrammingAndScripting/Online/Steam/

**Comment by mordentral** [comment]
for the record, the plugin doesn't interfere / alter the core subsystems at all, so if something DID break on the subsystems end, there is nothing I can do about it.

**Comment by cslak** [comment]
So yes, get game state> player array>length works fine

**Comment by cslak** [comment]
No, i do not use steamauth, as well as i am not using this: bInitServerOnClient=true

**Comment by cslak** [comment]
is steamauth required? is this(bInitServerOnClient=true) required to be enabled as well?

**Comment by mordentral** [comment]
what connection are you trying to get the persona name on even, the client or the server

**Comment by cslak** [comment]
server assigns it, pulls it from the clients playerstate

**Comment by mordentral** [comment]
UniqueID assignment isn't done by this plugin, if dedicated servers aren't filling that out anymore its on Epics end.
Obviously from the listen server perspective everything is working correctly here, and the unique net id assignment is engine side.

**Comment by mordentral** [comment]
I don't have a dedicated built to test against, but even if I did it wouldn't resolve that. They upped the steam SDK to a new version in 4.27 and broke quite a lot of things.

**Comment by cslak** [comment]
unique net id assigns fine, just checked it
Only thing doesnt get pulled properly is getsteampersonaname

**Comment by mordentral** [comment]
you said multiple times it was logging as unknown...

**Comment by cslak** [comment]
it is! just ran a few print strings, and it seems to assign the proper uniqueID

**Comment by mordentral** [comment]
i'll note, that as far as I knew dedicated servers shouldn't even have access to that portion of steam anyway. It was suprising to me that you said it was working in 4.26.

**Comment by cslak** [comment]
Yes 4.26 works just fine

**Comment by cslak** [comment]
do you know if usage of bInitServerOnClient=true is required?

**Comment by mordentral** [comment]
it is not, though generally you are supposed to be pulling persona names locally on clients anyway since they are always going to be connected to the steam api.
