### ISSUE TITLE
plugin added to project failes to compile in 4.25.3

### ISSUE THREAD

**Issue by unrealengine4u** [mordentral/AdvancedSessionsPlugin#3]
hi, I am trying to use the plugin and have added it to my project. I have gotten it to work before when I used it in 4.22 but this time around it fails to even compile. even after I have gone through and fixed it up so it compiles it does not actually connect to steam when running in standalone play (not pie). this is the compile issue i get with the stock plugin (no changes):
![image](https://user-images.githubusercontent.com/23741790/93528825-0c496e80-f98f-11ea-8f49-231848a64151.png)

**Comment by mordentral** [comment]
The UBT hides things in generated monolithic includes sometimes, I do need to add a player state include to that file.

The steam warning is of C4265 is a warning that is off by default and you are picking up it complaining about the steam source itself, there are several compiler warnings that are supposed to be turned off when including the steam api as it throws them.

As for the steam connection, that has nothing to do with the plugin itself, the subsystems are a seperate entity, the plugin just gives more access to calling functions on them. However 4.24 did add the new steam auth system and some target.cs compile time flags for steam that you should be using.

        /*
         * This is our Steam App ID.
         * # Define in both server and client targets
         */
        ProjectDefinitions.Add("UE4_PROJECT_STEAMSHIPPINGID=480");
