### ISSUE TITLE
Failed to get the account issue

### ISSUE THREAD

**Issue by T-Jeremy** [mordentral/AdvancedSessionsPlugin#34]
Hello,

I'm building a game using Advanced Sessions et Advanced Steam Session.

I'm using blueprints and UE V.5.0.1.

I got a working dedicated server and my client build is connecting to Steam (I can see and open the steam overlay)
I'm also able to retrieve the Steam Unique Net Id and Username in the `PlayerController` but I can't manage to use `Get User Account` using the correct Unique Net Id

I looked in the logs and saw this line : 
`AdvancedIdentityLog: Warning: GetUserAccount Failed to get the account!`

What can I do ?

**Comment by mordentral** [comment]
Those functions aren't implemented in the Steam Subsystems Identity Interface

`TSharedPtr<FUserOnlineAccount> FOnlineIdentitySteam::GetUserAccount(const FUniqueNetId& UserId) const
{
	//@todo - not implemented
	return NULL;
}
TArray<TSharedPtr<FUserOnlineAccount> > FOnlineIdentitySteam::GetAllUserAccounts() const 
{
	//@todo - not implemented
	return TArray<TSharedPtr<FUserOnlineAccount> >();
}`

**Comment by T-Jeremy** [comment]
Oh yes you're right, haven't seen that before, thank you.
