### ISSUE TITLE
Add compatible (tested) UE versions to README

### ISSUE THREAD

**Issue by Zenahr** [mordentral/AdvancedSessionsPlugin#41]
Please add supported UE versions that the plugin(s) have been successfully tested with.
On that note, does it work with UE 5.0.1?

**Comment by mordentral** [comment]
Master branch is always current released engine version, so its on 5.0.3 but would work on 5.0.1 since there were no source changes. Aside from that, every compatible branch besides latest current released engine is in its own branch.
