### ISSUE TITLE
Cannot build in UE5.0.3

### ISSUE THREAD

**Issue by Spongical** [mordentral/AdvancedSessionsPlugin#42]
"AdvancedSessions.precompiled" is missing from the build files when trying to package my game. 
Intermediate\Build\Win64\UnrealGame\Development\AdvancedSessions

**Comment by mordentral** [comment]
Don't place the plugin in your engine folder, place it at the project levelOn Jul 23, 2022 6:26 PM, Spongical ***@***.***> wrote:
"AdvancedSessions.precompiled" is missing from the build files when trying to package my game.
Intermediate\Build\Win64\UnrealGame\Development\AdvancedSessions
