### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by yigitmesut** [mordentral/AdvancedSessionsPlugin#44]
https://github.com/mordentral/AdvancedSessionsPlugin/blob/fd33fc34a502e838f0d0a6e1e8631b21b8bf44e5/AdvancedSessions/Source/AdvancedSessions/Private/LoginUserCallbackProxy.cpp#L68

Fixed by changing `FUniqueNetIdRepl` by `FUniqueNetIdPtr `

**Comment by mordentral** [comment]
What engine version are you on? Mismatching versions or compiling for UE5 Main will cause compilation issues.

**Comment by yigitmesut** [comment]
I'm on 4.27.2

**Comment by mordentral** [comment]
Where did you get your copy?

The 4.27 branch has had that corrected for 28 days. It only existed for a day or so before I noticed.

**Comment by yigitmesut** [comment]
Oh I see ... I take the `master` branch instead of `4.27-Locked` :(
