### ISSUE TITLE
Consider splitting the two plugins into separate repositories

### ISSUE THREAD

**Issue by dskvr** [mordentral/AdvancedSessionsPlugin#5]
Including both plugins makes integration particularly difficult in several cases.

1. There are cases where a **git submodule** is suitable, however, without this repo providing a branch that is a sub-tree of master, using **git submodules** is out of the question.
2. In the CI case, normally i would monitor the repo from automation based on a combination of UE4 conventions (.uplugin in root) and generic poly-repo standards (one component per repo). This automation would monitor changes to `master` (or more ideally, new **releases**), when changes are detected, the automation would package the plugin, tarball it and save it as an artifact for use in CI pipelines. While still possible, it requires that a special pipeline is created for this repo alone since it doesn't conform to either standard. I would have to pull the repo and cd to the specific subdirectory and then package the plugin. 

The current pattern is suitable for monorepos, but it is not obvious to me how a monorepo is beneficial to your offering.

Of course, there may be something I'm missing.

**Comment by mordentral** [comment]
You are separately enable / disable each module? Not sure I see the issue here.
