### ISSUE TITLE
LogOnlineSession: Warning: STEAM: Unable to set search parameter LOBBYSEARCH: Value=true : Equals : -1

### ISSUE THREAD

**Issue by OfficialAlienZ** [mordentral/AdvancedSessionsPlugin#51]
I'm currently using the public test ID (Spacewar, App ID 480) with this plugin. 

It works fine most of the time (players can join and host a game), but it may suddenly stop working for one player, not letting him join or host any match. It returns this error in the logs: "LogOnlineSession: Warning: STEAM: Unable to set search parameter LOBBYSEARCH: Value=true : Equals : -1". It may then start to work again after some time (could be minutes or hours).

I searched online for this error but I couldn't find any result.

**Comment by mordentral** [comment]
talked to in discord

**Comment by sjmduncan** [comment]
> talked to in discord

Have the same issue, what was the solution?
