### ISSUE TITLE
A question in UE5.0.3

### ISSUE THREAD

**Issue by Jeff-xue** [mordentral/AdvancedSessionsPlugin#52]
I use the EOS Plus. I created a Lobby through "Create Advanced Session", and another computer successfully joined the Lobby. However, in this Session, whether it is the "GetNumNetworkPlayers" method or the "Get PlayerArray" in the "Get Game State" method, the result is 1. However, it should be correct that there are 2 people. If the LAN is turned on, everything is OK.

I don't know what the problem is, project settings? Or is the method used incorrectly?

**Comment by mordentral** [comment]
Then i would go report that to the EOS plugin you are using for the subsystem. Neither of those have to do with AS and something isn't getting filled out correctly on the subsystems end.
