### ISSUE TITLE
Please upload separate repository  for (Advanced Sessions) and (Advanced steam Session)

### ISSUE THREAD

**Issue by iamsince1998** [mordentral/AdvancedSessionsPlugin#53]

**Comment by mordentral** [comment]
why? you can disable steam sessions in plugins directory

**Comment by iamsince1998** [comment]
> 

because when you update the plugin their is no notification and sometimes we miss it ,but now their a plugin on marketplace named as plugin downloader which can help us to download any plugin available on git. with update notifications but it can't process two plugins  
or 
upload the plugin on marketplace 

thanks
