### ISSUE TITLE
Downloaded plugin for UE5.0 but tells it need I to recompilate it

### ISSUE THREAD

**Issue by VELD-Dev** [mordentral/AdvancedSessionsPlugin#55]
I downloaded the plugin from the main/master branch, but when I put the plugin (AdvancedSession) into my Plugin folder, it tells me this:
![image](https://user-images.githubusercontent.com/36549174/201380309-56a2903b-4d4f-41c6-a4b6-03bf86641b34.png)
Then when I click YES it shows me this:
![image](https://user-images.githubusercontent.com/36549174/201380423-ec4d67a1-608f-423f-a0b2-147beea23ff2.png)
I tried also the 5.1 and 4.27 version, same thing...
My current version of the engine is 5.0.3.

**Comment by matteo-chevalier** [comment]
How did you solve it ?
