### ISSUE TITLE
Mac OS X Ventura - Project not starting

### ISSUE THREAD

**Issue by discozone** [mordentral/AdvancedSessionsPlugin#57]
On Mac OS X Ventura, the plugin seems broken, as the project won't open, saying that the plugin need to be rebuilt.
Unfortunately, UE5 tells me that the plugin "could not be built. Try rebuild them manually".

Any ideas ?

Mac M1 - OS X Ventura 13.0.1
XCode 14
UE 5.0.3
Advanced Sessions 5.0

**Comment by mordentral** [comment]
I cannot create pre-compiled binaries for mac, it has to be built by you in the IDE
