### ISSUE TITLE
Mind adding a short section on how to build the plugin to the README?

### ISSUE THREAD

**Issue by Zenahr** [mordentral/AdvancedSessionsPlugin#6]
For example I don't know at first glance if I'd have to build `AdvancedSessions` even if I only wanted to use `AdvancedSessionsSteam`.

Adding a short section in the README outlining what has to be added to the `ProjectName.build.cs` file would be aweseome.

**Comment by mordentral** [comment]
@Zenahr you don't need to add it to the build.cs if using it as a BP plugin, only if trying to call into it from code (which you shouldn't be doing generally). Its a plugin to expose what already exists in C++ to BP.

I did have an installation notice on the old repo, must have forgotten to port it over.

**Comment by Zenahr** [comment]
I was trying to add it to a cpp based project and if I remember correctly it said the modules had to be rebuilt and I got compilation errors.

**Comment by mordentral** [comment]
They have to be built in visual studio yes, but you don’t have to add them to build.cs, just add them to the plugins folder and regenerate your project files and compile.
