### ISSUE TITLE
EOS_Auth_ScopeConsentRequired 

### ISSUE THREAD

**Issue by iamsince1998** [mordentral/AdvancedSessionsPlugin#60]
hi , please help me how to solve this problem(EOS_Auth_ScopeConsentRequired)
![Screenshot (6)](https://user-images.githubusercontent.com/91234637/206634728-7a8b7ed9-0874-4564-a1f4-001626351c73.png)

**Comment by mordentral** [comment]
I don't work with EOS and this is unrelated to AS, you be better off asking the EOS discord channel
