### ISSUE TITLE
Cant create session with local controllers where local ID not 0

### ISSUE THREAD

**Issue by rewb0rn** [mordentral/AdvancedSessionsPlugin#62]
Hi,

I have built a start screen in which the user can "hit A" on any controller to initialize the player controller he wants to use. I do this by creating up to 4 local players (setting split screen to disabled). Once the user hits A on his favorite XBOX / PS controller, I will destroy the other player controllers.

Using any player controller other than the one on index 0 will fail to create an Advanced session with error message:

`LogScript: Warning: Script Msg: Invalid Player controller when attempting to start a session`

I checked the code and this seems to happen when the UniqueNetId of a player controller is invalid. I am using the default online system null (with LAN) for testing right now.

I can work around this problem by setting the local controller ID to 0 on the chosen player controller and that will allow me to create the session and then setting the local ID back to the correct value afterwards. However after a map change the controller will regenerate the same error message on the DestroySession call, and nothing I tried seems to fix it. I believe this is because when the next map loads and the PlayerStates are created, the index of the player controller ingame is now different than it was in the main menu (due to the fact that in main menu, the user has chosen the XBOX controller associated with a player controller != 0, but on the next map it becomes index 0, since I have removed the not needed remaining player controllers).

I checked the C++ code and it seems C++ generally favors to handle sessions via the SessionName, which would probably fix my specific issue, but these are not exposed via Blueprint. Any ideas on a workaround?

Thanks

**Comment by mordentral** [comment]
The unique net id is stored on the playercontroller and in the case where there is only one local player signed into the service only index 0 has a valid ID. Create session requires both the unique net ID AND the session name, its not one or the other, null isn't a really good representation of this either as you would have more problems with a real subsystem and the workaround you tried to do there.

**Comment by rewb0rn** [comment]
Thanks for your reply and the clarification! I will make more tests with the actual online subsystem and in the worst case just require the user to use the first physical controller when playing online!

**Comment by rewb0rn** [comment]
Update for anyone reading: Maybe I was just overengineering in my first attempt to get this to working. I removed all of the above mentioned workaround and instead set local player controller id of the desired physical controller id on GetPlayerController(0) instead, this seems to have fixed all my issues. Verified this is working fine for both subsystem null and EOS.

Thanks for your help!
