### ISSUE TITLE
AdvancedSteamFriendsLibrary.h errors

### ISSUE THREAD

**Issue by worbarry** [mordentral/AdvancedSessionsPlugin#63]
after adding plugin to my projects plugin directory i get this error along with others on that file in visual studio.

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E1455	member function declared with 'override' does not override a base class member	fpsProject	F:\Unreal Projects\fpsProject\Plugins\AdvancedSteamSessions\Source\AdvancedSteamSessions\Classes\AdvancedSteamFriendsLibrary.h	198

**Comment by mordentral** [comment]
You do not have the matching plugin version to engine version.
