### ISSUE TITLE
Session State not change on client when host leave session

### ISSUE THREAD

**Issue by JohansenJunias20** [mordentral/AdvancedSessionsPlugin#64]
when the client calls the "get session state" node it returns "Pending" state after the room destroy because the host leaves the session.
Note:
Session created with `bStartAfterCreate=False`
the room has not been started yet by the host.
tested on Online Subsystem NULL (not yet steam)

**Comment by mordentral** [comment]
Clients also still have to call DestroySession when leaving one or when one dies out from under them.

I understand epics naming of that function is rather obtuse, but its a requirement
