### ISSUE TITLE
BucketId for EOS sessions

### ISSUE THREAD

**Issue by rewb0rn** [mordentral/AdvancedSessionsPlugin#65]
Hello,

is there a way to specify the BucketId for creating a session using the online subsystem Epic Online Services? We found that the BucketId is created automatically and containing the unreal engine version, which prevents us from testing this in our team where I use UE5 source and my coworker UE5 from the Epic Store. Since BucketIds are the main search criteria, we can not work around this issue currently.

More info on the BucketId and how to set it here:
https://dev.epicgames.com/docs/game-services/sessions

We tried adding a SessionProperty String "BucketId" in the ExtraSettings property of the CreateAdvancedSession node, but to no avail, we still see the automated BucketId being used for our session in the Epic Online Services developer portal.

Thanks in advance

**Comment by mordentral** [comment]
Try with this param (in the TEXT), they have a section in EOS's session system where it searches for this custom setting and overrides the Bucket value with it.

static FName EOSGS_BUCKET_ID_ATTRIBUTE_KEY = TEXT("EOSGS_BUCKET_ID_ATTRIBUTE_KEY");

**Comment by rewb0rn** [comment]
Thank you! I guess this goes to the ExtraSettings, I added it there with "MakeLiteralSessionPropertyString" and I can see the attribute is added in the session dashboard. However the BucketId is unchanged, see screenshot below. I noticed a little "_s" is appended to the key name to signal it's a String property, could this prevent it from being parsed in the EOS session system?

![SessionBucket](https://user-images.githubusercontent.com/1615003/214679392-e34a1839-ce0e-486d-8cc6-9d827647cbee.png)

**Comment by rewb0rn** [comment]
Alright after spending some time in the source code and comparing engine versions, it seems that the code that you mentioned was introduced in the new online systems of 5.1, but we are still sitting on 5.0.3. I have slightly modified the way the initial bucket id is created in the EOS Online Subsystem (and created a PR), but either way this is not an issue of this plugin.

Thanks for your help!
