### ISSUE TITLE
Blueprint Advanced sessions login to login to Epic Games EOS Logs onto apple Game Center instead (Support for IOS)

### ISSUE THREAD

**Issue by appandgametech** [mordentral/AdvancedSessionsPlugin#67]
Hi folks I am building on Mac, for IOS platform, using unreal engine 5.1.1, and I have run into an issue while I am doing initial phase of getting advanced sessions setup for iOS, I setup blueprints to login to epic games, this works when I play in stand alone game, however when I package my game for iOS. nothing happens, with the stand alone game my web browser is launched and directs me to login to epic games, im thinking that while on my iOS device it doesn’t know to launch the browser, any idea how I can do this, or maybe I can use the unreal engine browser to go into epic games site to login ? here is my current blue print im using that logs into epic games when I click a button on a widget. It seems when I press the login button as stated in the blueprints, on my iOS phone it logs me into my apple Game Center account instead of routing me to epic games via launching my mobile web browser and promoting me to go through the login flow.

![082a8d2ab27733d52d3812adbed9ea9942ed90da_2_690x349](https://user-images.githubusercontent.com/76648682/230839432-6738762a-37e2-4a2b-b4fa-242355d61e31.jpeg)

**Comment by appandgametech** [comment]
update here is the backtrace from Xcode of my crash, it looks like the issue occurred on line 3 below "3   MultipeerConnectivity         	0x230c6a694 -[MCPeerID initWithDisplayName:] + 176 (MCPeerID.m:178)"

I think calling the bp login user thinks im trying to call login user to login to apple Game Center. as when I press the button Game Center logins. 


0   CoreFoundation                	0x1cb23ce38 __exceptionPreprocess + 164 (NSException.m:202)
1   libobjc.A.dylib               	0x1c43c78d8 objc_exception_throw + 60 (objc-exception.mm:356)
2   CoreFoundation                	0x1cb32cc28 +[NSException raise:format:] + 112 (NSException.m:0)
3   MultipeerConnectivity         	0x230c6a694 -[MCPeerID initWithDisplayName:] + 176 (MCPeerID.m:178)
4   ReadyPlayer                   	0x1035f5b18 0x1021d0000 + 21125912
5   ReadyPlayer                   	0x1035f5e64 0x1021d0000 + 21126756
6   ReadyPlayer                   	0x1035f75a4 0x1021d0000 + 21132708
7   ReadyPlayer                   	0x102c42f84 0x1021d0000 + 10956676
8   ReadyPlayer                   	0x102c4be74 0x1021d0000 + 10993268
9   ReadyPlayer                   	0x10289cb54 0x1021d0000 + 7129940
10  ReadyPlayer                   	0x1035f7474 0x1021d0000 + 21132404
11  ReadyPlayer                   	0x102c43828 0x1021d0000 + 10958888
12  ReadyPlayer                   	0x104161918 0x1021d0000 + 33102104
13  ReadyPlayer                   	0x104286b08 0x1021d0000 + 34302728
14  ReadyPlayer                   	0x10428e0f8 0x1021d0000 + 34332920
15  ReadyPlayer                   	0x104287134 0x1021d0000 + 34304308
16  ReadyPlayer                   	0x104286d4c 0x1021d0000 + 34303308
17  ReadyPlayer                   	0x104287134 0x1021d0000 + 34304308
18  ReadyPlayer                   	0x104161918 0x1021d0000 + 33102104
19  ReadyPlayer                   	0x1042883b8 0x1021d0000 + 34309048
20  ReadyPlayer                   	0x10279c94c 0x1021d0000 + 6080844
21  ReadyPlayer                   	0x102c47ffc 0x1021d0000 + 10977276
22  ReadyPlayer                   	0x102c4d044 0x1021d0000 + 10997828
23  ReadyPlayer                   	0x10289c470 0x1021d0000 + 7128176
24  ReadyPlayer                   	0x1035ef224 0x1021d0000 + 21099044
25  ReadyPlayer                   	0x103fcc600 0x1021d0000 + 31442432
26  ReadyPlayer                   	0x103fcc698 0x1021d0000 + 31442584
27  ReadyPlayer                   	0x104307538 0x1021d0000 + 34829624
28  Foundation                    	0x1c55f5518 __NSThread__start__ + 716 (NSThread.m:963)
29  libsystem_pthread.dylib       	0x2194b56cc _pthread_start + 148 (pthread.c:893)
30  libsystem_pthread.dylib       	0x2194b4ba4 thread_start + 8

**Comment by mordentral** [comment]
Login user simply calls the current active subsystems LoginUser, it does not perform any of the logic itself.

**Comment by appandgametech** [comment]
Thanks @mordentral for your reply. When calling the login function, as in the screenshot below, if I play in standalone game mode in unreal engine 5.1.1 when I click the button to call this function then it opens up a web browser and tells me to sign in to epic games account. but the problem is when I package and deploy to mobile its not doing that. How can I tell the function to open up my safari web browser and do the same to take me to the unreal engine login page, or is the documentation I can follow for the mobile implementation.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/76648682/231619760-9fec3c02-d55e-4c10-a4fc-bce9246b8520.png">

**Comment by mordentral** [comment]
I wouldn't know, its not my subsystem and I haven't used it. AS just interfaces with whatever subsystem you are using. You would have to look at EOS documents.

**Comment by nicolasporion** [comment]
> Thanks [@mordentral](https://github.com/mordentral) for your reply. When calling the login function, as in the screenshot below, if I play in standalone game mode in unreal engine 5.1.1 when I click the button to call this function then it opens up a web browser and tells me to sign in to epic games account. but the problem is when I package and deploy to mobile its not doing that. How can I tell the function to open up my safari web browser and do the same to take me to the unreal engine login page, or is the documentation I can follow for the mobile implementation.
> 
> <img alt="image" width="1061" src="https://user-images.githubusercontent.com/76648682/231619760-9fec3c02-d55e-4c10-a4fc-bce9246b8520.png">

Hi @appandgametech I'm completely stuck in the same issue than you described :( Did you finally find any solution for that? Even if it's been almost 3 years ago ^^

**Comment by mordentral** [comment]
Bug report it to epic, they will never fix it otherwise
