### ISSUE TITLE
How can i get this available on Mac?

### ISSUE THREAD

**Issue by ErcouldnT** [mordentral/AdvancedSessionsPlugin#68]
Project had compiler error and not opening when i copy plugin folders to my plugins folder.

**Comment by appandgametech** [comment]
HI, Ah so your on Mac too, same version huh, unreal engine developing with Mac, I know the pain, feels sometimes folks forgetting about us Mac users when it comes to unreal engine. I bet we run into very similar issues ie Mac users get little love from UE, but thats for another day. 

So regarding your issue, 

Ok so can you do me a favor and first try to remove the advanced steam sessions, and see if the advanced sessions plugin loads up successfully. 

If that still is an issue, please delete the following folder from your project (BEFORE YOU DO THIS PLEASE BACK UP YOUR PROJECT)

Delete the folders boxed in purple in the screenshot below

![image](https://user-images.githubusercontent.com/76648682/231898013-54572e17-cd3d-4437-a517-7f62ce0cbfc4.png)


The reason I said remove advanced steam sessions for now is I think I ran into that same problem with that specific plugin and then ended up never fixing it. but let me also confirm shortly. I just want to make sure at least the first plugin works for you, so we can say we both have the same issue going on. ie with the second plugin.

**Comment by mordentral** [comment]
Its telling you to compile the plugin in XCode, launching the project won't compile the plugin and I don't have the hardware to ship pre-compiled MacOS binaries.

**Comment by mordentral** [comment]
https://docs.unrealengine.com/5.0/en-US/setting-up-an-unreal-engine-project-for-ios/

**Comment by mordentral** [comment]
the general concept, i am not aware of tutorials for this really as I have never had to do it.
