### ISSUE TITLE
Let's compile all libraries for MacOS

### ISSUE THREAD

**Issue by ErcouldnT** [mordentral/AdvancedSessionsPlugin#69]
Guys, I have latest Xcode version on my Mac. I need to compile this plugin to build a game on Mac.

I don't know how to compile for Mac.

Let's get contact for compiling project on Mac. So, we can update the repo for Mac users as well.

**Comment by mordentral** [comment]
AFAIK it should compile for mac as is already as I believe that others have used my VR plugins example on mac and it includes this  module. However, yes, I have no way of testing this myself.

**Comment by mordentral** [comment]
> Quick update: Unreal Engine 5.2 released. AdvancedSessions 5.2 compiles perfectly. Game build is perfect on MacOS.
> 
> So I'm telling you @mordentral possibly the difference between AdvancedSessions 5.1.1 and 5.2 is causing compile error on 5.1.1.

It is the same branch for Advanced Sessions in 5.1 and 5.2. I made a change for MacOS several weeks ago but it was in 5.1's source copy as well. Unless you were using the precompiled binaries, then sure it could have been a problem for  you.
