### ISSUE TITLE
Problem with connecting to port when using Steam connection?

### ISSUE THREAD

**Issue by wzGCU** [mordentral/AdvancedSessionsPlugin#7]
Hey there!
I have a problem with the plugin. When I'm using the steam connection with the Create Advanced Session, and then in-game start 'Host', it loads the map only for a split second and then it kicks me out back to menu. It seems like I have some problem with SteamSocket? Do not really know how to fix that although was searching all over internet and could not found solution. I tried enabling SteamSocket plugin in unreal but it throws similiar error.

![image](https://user-images.githubusercontent.com/61721211/107245613-a0e06600-6a2f-11eb-94ec-37286e1757c8.png)

**Comment by mordentral** [comment]
Not an issue with the plugin itself, you are running into an engine misconfiguration likely, also chances are good it is this fairly common mistake in setting up your configs.

https://answers.unrealengine.com/questions/305216/steamsockets-binding-to-port-7777-failed.html
