### ISSUE TITLE
EOS Voice | Push to talk not working

### ISSUE THREAD

**Issue by JTG89** [mordentral/AdvancedSessionsPlugin#70]
Hey,

After connecting to a session, the voice is working and we can hear each other. However, Start and Stop Networked Voice is not.
Push to talk simply does not work in the way we implemented it.

I added 
```
[/Script/Engine.GameSession]
bRequiresPushToTalk=true
```

to the `DefaultGame.ini`.

And 

```
[Voice]
bEnabled=true

[OnlineSubsystem]
DefaultPlatformService=EOS
bHasVoiceEnabled=true
```
to the `DefaultEngine.ini`.

When I try to use Start or Stop Networked Voice, or `isLocalPlayerTalking` I get the warning:

`(Method) couldn't get the voice interface!`

Where Method is isLocalPlayerTalking or also Start Stop Netwrorked Voice

![image](https://github.com/mordentral/AdvancedSessionsPlugin/assets/133156450/05a8c7fc-d121-4b39-bc53-b82a20b5fee3)

I setup the state.

And use a button to call Start and Stop Netwroked Voice:

![image](https://github.com/mordentral/AdvancedSessionsPlugin/assets/133156450/d8f4cdb0-a49b-4dfe-badb-bd64419e9d48)

Do you have any ideas about what I am doing wrong?

**Comment by mordentral** [comment]
Are you actually using the voice interface? Those nodes only work  with the engines built in voice interface.
