### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by Jeff-xue** [mordentral/AdvancedSessionsPlugin#71]
![QQ图片20230524143357](https://github.com/mordentral/AdvancedSessionsPlugin/assets/21231211/dede528f-cea3-48a6-8d22-9ff60a6685c7)

Hi, I'm having a problem with a failed login.
I am using the EOSPlus feature and after using "Login User", I keep getting stuck at the account connection screen. This problem appeared about 2 days ago, but last week it was fine.

Now it says "Your Epic Games Account and Steam Account are already linked."
But after I click "continue", it keeps popping up this account connection screen in a repeated loop.

**Comment by mordentral** [comment]
That doesn't have anything to do with this plugin?
