### ISSUE TITLE
User auto login

### ISSUE THREAD

**Issue by AidenForrest** [mordentral/AdvancedSessionsPlugin#75]
Hi,

Thank you for helping my project with this plugin its very useful and made EOS a breeze.

I was trying to figure out how to make it auto-login the user the next time they launch the game rather than having to go through the hassle of logging in and completing 2FA all over again, but I couldn't figure it out.

Any help would be greatly appreciated, thanks!

**Comment by Scylin232** [comment]
As far as I remember, this only happens if your app is not trusted in the Epic Games Portal, do you have trust?

**Comment by AidenForrest** [comment]
No, not yet I haven't submitted it to be trusted yet I'll give that a try and see how it works thank you for your help

**Comment by AidenForrest** [comment]
> As far as I remember, this only happens if your app is not trusted in the Epic Games Portal, do you have trust?

Hi, my game is now trusted yet it still logs me out every time and I have to re log in and complete 2FA and re-captcha. Is there some extra code I have to add also currently I just have the 'Login user' node as seen in the attached image.

Thanks!

![image](https://github.com/mordentral/AdvancedSessionsPlugin/assets/79009276/6924b093-272d-42aa-8dde-6081db9cc23a)

**Comment by AidenForrest** [comment]
Hi,

I've been trying to mess around with different builds but I still can't seem to get it to work. Does anyone know how to get this to work?

Thanks, Aiden

**Comment by mordentral** [comment]
AFAIK others are using it currently as is already, but I don't really keep up on EOS specific things.

**Comment by AidenForrest** [comment]
Hi thanks for your reply. I know you have some projects listed in your website that use your plugins. Do you know if any of them use EOS and if so, could you point me towards them please so I can get in touch. 

Cheers

**Comment by AidenForrest** [comment]
Ok I'll take a look thanks

**Comment by AidenForrest** [comment]
Managed to get it working. Wa using outdated auth type. Should have been persistentauth auth type
