### ISSUE TITLE
I cannot use this plugin...

### ISSUE THREAD

**Issue by redtyyt** [mordentral/AdvancedSessionsPlugin#80]
Please, I'm creating a game with only blueprints (consider my issue pls).
I have some _problems_ with this plugin and with UE5.2.

**Comment by mordentral** [comment]
No idea what your issue is? Do you mind detailing it?

**Comment by redtyyt** [comment]
Yes, excuse me. I have Unreal Engine.5.1 and I installed this plugin. Then, I configured the EOS Online Subsystem with the `defaultengine.ini`file. This is It:
> `[OnlineSubsystemEOS]
bEnabled=true

[OnlineSubsystem]
DefaultPlatformService=EOS

[/Script/Engine.GameEngine]
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="OnlineNetDriverEOS",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")

[/Script/OnlineSubsystemEOS.NetDriverEOS]
bIsUsingP2PSockets=false`

What I should do?
# I need to enable P2P sockets on the DefaultEngine.ini and in EOS Developer Portal?
IDK...

**Comment by redtyyt** [comment]
Ok, thanks, but who can resolve this "Issue"?

**Comment by mordentral** [comment]
Epics official documents and the EOS section of the UE devs discord.
