### ISSUE TITLE
Fatal Error on Packaged Game Launch UE 5.3.2

### ISSUE THREAD

**Issue by geohan98** [mordentral/AdvancedSessionsPlugin#85]
Hi,
I am currently getting a fatal error on a brand new third person template with the plugin enabled, I have at least one c++ class in the project, and I have enabled the online subsystem steam, as this wasnt enabled after adding the plugin.

https://pastebin.com/RE8BM3dH

Thanks

**Comment by mordentral** [comment]
In 5.3 I had to rip declaring the steam subsystem as a dependency out as epic screwed something up with it. Part of that is also that it doesn't package out the steam dll to the exe directory anymore. Search the packaged directory for the steam dll and place it inside of the exe directory. Hopefully in 5.4 everything will be sorted again.
