### ISSUE TITLE
Plugin nativization

### ISSUE THREAD

**Issue by mjaglarz** [mordentral/AdvancedSessionsPlugin#9]
Hi,
Thanks for this plugin! It's doing the job. I wanted to ask, is it possible to nativize this plugin? I had some problems in the past with plugin nativization and quite often it doesn't work.

**Comment by mordentral** [comment]
It was working last time I checked yes, and I check each engine version. However nativization breaks quite often in engine (not really different plugins faults normally), likely why its being removed in UE5.

**Comment by Cesio137** [comment]
> It was working last time I checked yes, and I check each engine version. However nativization breaks quite often in engine (not really different plugins faults normally), likely why its being removed in UE5.

@mordentral can you tell me How you did the setup of plugin. In ue4.26.1 nativizate works fine but after that não ivizate broken my project and i need it

**Comment by mordentral** [comment]
Broke it how? it should be spitting out errors for you on packaging if nativization is failing.

**Comment by Cesio137** [comment]
@mordentral I left the advanced session(steam and Lan) in the plugins folder, and configured the project in c++ and the config folder. In version 4.26.1 when I used nativizated everything worked fine, but after the update to 4.26.2 the plugin is failing when I activate nativizated. I would like to know how you configured the plugin to not give an error?

Tutorial i saw: https://youtu.be/EDNF2DNLhPc

OBS: I report an error in a previous post and it seems to only happen with the "advanced session"

public: __cdecl AAdvancedGameSession::AAdvancedGameSession(class FObjectInitializer const &)

**Comment by mordentral** [comment]
I didn't test it in .2, but its not uncommon for even hotfixes to break nativization, I stopped trying to track it too closely as this is all based off of their automatic code generation and I have very little control over the bugs that it creates.

**Comment by Cesio137** [comment]
@mordentral ok thanks at all, but pliss if you can fix this plugin i will be very grateful

**Comment by mordentral** [comment]
I believe that I already told you, but I will specifically state it. I cannot fix their nativisation bugging out in it's generation, it's a bug on their end not mine. Which is likely why ue5 is dropping it. I stopped suggesting that people fully nativize a long time ago and suggest that they only nativize classes that need it.
