### ISSUE TITLE
Blueprint NetIDs not replicating

### ISSUE THREAD

**Issue by Mr4Goosey** [mordentral/AdvancedSessionsPlugin#96]
Hi,

I'm running into a variety of issues with regards to Unique NetIDs not replicating. No matter what I do, NetIDs set on the server and replicated to the client are returned invalid on the client. I'm using the precompiled plugin binaries on 5.4.4.

See this image for a straight-forward example:
![image](https://github.com/user-attachments/assets/393925eb-68a1-4eeb-b92e-426fbd64d55d)
In this case, the server has set the variable with notify, and the notify runs on the server. The notify never runs on the client, and the client continues to log an invalid NetID.

I'm currently working around this issue by turning my NetIDs into strings before replicating, which works for now, but it does feel somewhat undesirable.

Is this expected behaviour? 
Thanks!

**Comment by mordentral** [comment]
Yes its expected, unique net ids change per system and generally there is no reason to ever have to replicate the BP version of them. The player state array lets you get the unique net ids of members of the server anyway, they are already replicated for you.
